version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: daEIUF82hdd8_a2f
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ckj32fn3-df3a2j
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: daEIUF82hdd8_a2f
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ckj32fn3-df3a2j
    networks:
      - wpsite
  # App
  # app:
  #   depends_on:
  #     - wordpress
  #   restart: always
  #   build: .
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - '.:/app'
  # frontend:
  #   command: bash -c 'npm install && npm start'
  #   container_name: frontend
  #   expose:
  #     - '3000'
  #   restart: always
  #   image: node
  #   ports:
  #     - '3000:3000'
  #   user: node
  #   volumes:
  #     - ./frontend:/home/node/app
  #   working_dir: /home/node/app
  frontend:
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
    command: npm run start
    build: ./frontend
    ports:
      - 3000:3000

    networks:
      - wpsite

networks:
  wpsite:
volumes:
  db_data:
